// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT_vRcvqJW5W5QJ1SQb15pBbzMakouqDQ',
    appId: '1:1052648401058:android:416c239049827477ee8ffb',
    messagingSenderId: '1052648401058',
    projectId: 'ditonton-82a7c',
    storageBucket: 'ditonton-82a7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxe77G2DPAZITBF3Qe7-8U1oM2rC8wxRM',
    appId: '1:1052648401058:ios:9a07b3ddad9e305fee8ffb',
    messagingSenderId: '1052648401058',
    projectId: 'ditonton-82a7c',
    storageBucket: 'ditonton-82a7c.appspot.com',
    iosClientId: '1052648401058-a38foc54dbflv5r4475l50fq1tnuj3c3.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
